In [17]:
import numpy as np

#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]]) # here, our i/p X is a data matrix of size 3*4
print("shape of input = ", X.shape)

#Output
y=np.array([[1],[1],[0]]) # output y takes size of 3*1

# defining our own Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

# Derivative of Sigmoid Function to update gradients while back propogating
def derivatives_sigmoid(x):
    return x * (1 - x) # this is derivative of sigmoid function

#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting our own learning rate
inputlayer_neurons = X.shape[1] #number of features in data set(X.Shape[1] returns 4 in (3,4) tuple)
hiddenlayer_neurons = 3 #number of hidden layers neurons (pre-defined)
output_neurons = 1 #number of neurons at output layer (pre-defined, should be 1 for simple architechture)

#weight and bias initialization

wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
# o/p should be a 4*3 matrix with random numbers b/w 0&1.here, we intialize weights b/w 1st & 2nd layers

bh=np.random.uniform(size=(1,hiddenlayer_neurons))
# o/p should be a 1*3 matrix with random no's b/w 0&1.here, we intialize bias term of i/p layer

wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
# o/p should be a 3*1 matrix with random no's b/w 0&1.here, we intialize weights b/w 2nd & o/p layer

bout=np.random.uniform(size=(1,output_neurons))
# o/p should be a 1*1 matrix with random no's b/w 0&1.here, we intialize bias term of hidden layer

print("weights intialized between i/p and hidden layers :\n",wh)
print("bias intialized at hidden layer :\n", bh)
print("weights intialized between hidden and o/p layer :\n",wout)
print("bias intialized at o/p layer :\n",bout)

for i in range(epoch): # 1 FORWARD + 1 BACKWARD propogation = 1 EPOCH 

    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh) #dot product b/w input matrix(3*4) and weights of i/p layer(4*3)=(3*3 matrix)
    hidden_layer_input=hidden_layer_input1 + bh #just adding a scalar-value of bias term
    hiddenlayer_activations = sigmoid(hidden_layer_input) # applying sigmoid non-linear function to (3*3 matrix)
    output_layer_input1=np.dot(hiddenlayer_activations,wout) # dot-pro b/w prev.o/p & present weights(result=3*1)
    output_layer_input= output_layer_input1+ bout # addition of hidden-layer bias term(3*1)
    output = sigmoid(output_layer_input) # applying sigmoid-activation to o/p (3*1)matrix
    print("output we got at epoch ",i," \n",output) # SHOULD BE 3*1 MATRIX
    print("===================================================================================")

    #Backpropagation
    E = y-output #defining our error term (3*1)matrix--->diff. b/w defined o/p and o/p we got (ERROR)
    slope_output_layer = derivatives_sigmoid(output) # calculating derivative at o/p layer
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations) #derivative at hidden-layer
    d_output = E * slope_output_layer # error * (derivative we calculated at o/p layer)(3*1 matrix)
    #print("*******************************",slope_output_layer.shape,"****************************")
    Error_at_hidden_layer = d_output.dot(wout.T) # a dot product b/w (3*1) and (1*3) matrix (chain-rule)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer # calculating delta of hidden layer(3*3 matrix)
    wout += hiddenlayer_activations.T.dot(d_output) *lr #(update o/p weights using prev. derivatives and lr)
    bout += np.sum(d_output, axis=0,keepdims=True) *lr#(update bias terms with sum of prev. partial derivatives)
    wh += X.T.dot(d_hiddenlayer) *lr # update hidden weights using input matrix and delta of hidden layer
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr # update hidden bias term

print("final output, \n",output)

shape of input =  (3, 4)
weights intialized between i/p and hidden layers :
 [[0.01490053 0.10103401 0.60982884]
 [0.09730739 0.47708051 0.77075476]
 [0.31033676 0.15632244 0.64027   ]
 [0.43397756 0.634222   0.08643442]]
bias intialized at hidden layer :
 [[0.15937787 0.21903562 0.64903215]]
weights intialized between hidden and o/p layer :
 [[0.29182096]
 [0.68437182]
 [0.1229377 ]]
bias intialized at o/p layer :
 [[0.42916297]]
output we got at epoch  0  
 [[0.75747191]
 [0.77913861]
 [0.77996132]]
output we got at epoch  1  
 [[0.75503943]
 [0.77663601]
 [0.77739845]]
output we got at epoch  2  
 [[0.75263219]
 [0.77415566]
 [0.77485685]]
output we got at epoch  3  
 [[0.75025182]
 [0.77169935]
 [0.77233833]]
output we got at epoch  4  
 [[0.74789987]
 [0.76926879]
 [0.76984462]]
output we got at epoch  5  
 [[0.74557782]
 [0.76686561]
 [0.76737737]]
output we got at epoch  6  
 [[0.74328707]
 [0.76449138]
 [0.76493817]]
output we got at epoch  7  
 [[0.74102894]
 [0.76214758]
 [0.

 [0.65576865]]
output we got at epoch  311  
 [[0.68361496]
 [0.69437919]
 [0.65559471]]
output we got at epoch  312  
 [[0.68373357]
 [0.69448296]
 [0.65541885]]
output we got at epoch  313  
 [[0.68385271]
 [0.69458709]
 [0.65524105]]
output we got at epoch  314  
 [[0.68397239]
 [0.69469158]
 [0.65506128]]
output we got at epoch  315  
 [[0.68409261]
 [0.69479645]
 [0.65487954]]
output we got at epoch  316  
 [[0.68421339]
 [0.69490168]
 [0.6546958 ]]
output we got at epoch  317  
 [[0.68433472]
 [0.69500729]
 [0.65451003]]
output we got at epoch  318  
 [[0.68445661]
 [0.69511328]
 [0.65432222]]
output we got at epoch  319  
 [[0.68457907]
 [0.69521964]
 [0.65413235]]
output we got at epoch  320  
 [[0.68470211]
 [0.69532638]
 [0.65394039]]
output we got at epoch  321  
 [[0.68482572]
 [0.69543351]
 [0.65374632]]
output we got at epoch  322  
 [[0.68494992]
 [0.69554102]
 [0.65355012]]
output we got at epoch  323  
 [[0.6850747 ]
 [0.69564892]
 [0.65335176]]
output we got at epoch 

output we got at epoch  524  
 [[0.7355149 ]
 [0.73268815]
 [0.53420818]]
output we got at epoch  525  
 [[0.7359664 ]
 [0.73300461]
 [0.53311951]]
output we got at epoch  526  
 [[0.73642018]
 [0.73332286]
 [0.53202714]]
output we got at epoch  527  
 [[0.73687621]
 [0.73364289]
 [0.53093112]]
output we got at epoch  528  
 [[0.73733449]
 [0.7339647 ]
 [0.52983153]]
output we got at epoch  529  
 [[0.737795  ]
 [0.73428828]
 [0.52872844]]
output we got at epoch  530  
 [[0.73825772]
 [0.73461364]
 [0.52762191]]
output we got at epoch  531  
 [[0.73872264]
 [0.73494076]
 [0.52651201]]
output we got at epoch  532  
 [[0.73918974]
 [0.73526964]
 [0.52539882]]
output we got at epoch  533  
 [[0.73965899]
 [0.73560028]
 [0.52428239]]
output we got at epoch  534  
 [[0.74013039]
 [0.73593267]
 [0.52316281]]
output we got at epoch  535  
 [[0.74060391]
 [0.73626681]
 [0.52204014]]
output we got at epoch  536  
 [[0.74107953]
 [0.73660268]
 [0.52091446]]
output we got at epoch  537  
 [[0.741

output we got at epoch  798  
 [[0.86252736]
 [0.83632121]
 [0.27321403]]
output we got at epoch  799  
 [[0.86282917]
 [0.83661274]
 [0.27263978]]
output we got at epoch  800  
 [[0.86312971]
 [0.83690331]
 [0.27206793]]
output we got at epoch  801  
 [[0.863429  ]
 [0.83719293]
 [0.27149846]]
output we got at epoch  802  
 [[0.86372704]
 [0.83748158]
 [0.27093137]]
output we got at epoch  803  
 [[0.86402383]
 [0.83776928]
 [0.27036664]]
output we got at epoch  804  
 [[0.86431939]
 [0.83805602]
 [0.26980427]]
output we got at epoch  805  
 [[0.8646137 ]
 [0.83834182]
 [0.26924423]]
output we got at epoch  806  
 [[0.86490679]
 [0.83862666]
 [0.26868653]]
output we got at epoch  807  
 [[0.86519866]
 [0.83891056]
 [0.26813114]]
output we got at epoch  808  
 [[0.86548931]
 [0.83919352]
 [0.26757806]]
output we got at epoch  809  
 [[0.86577874]
 [0.83947554]
 [0.26702727]]
output we got at epoch  810  
 [[0.86606697]
 [0.83975662]
 [0.26647877]]
output we got at epoch  811  
 [[0.866

 [0.18364285]]
output we got at epoch  1038  
 [[0.90941451]
 [0.88487672]
 [0.18340389]]
output we got at epoch  1039  
 [[0.90953739]
 [0.88501304]
 [0.18316567]]
output we got at epoch  1040  
 [[0.90965987]
 [0.88514896]
 [0.18292818]]
output we got at epoch  1041  
 [[0.90978196]
 [0.88528451]
 [0.18269143]]
output we got at epoch  1042  
 [[0.90990367]
 [0.88541967]
 [0.18245541]]
output we got at epoch  1043  
 [[0.91002499]
 [0.88555446]
 [0.18222012]]
output we got at epoch  1044  
 [[0.91014593]
 [0.88568886]
 [0.18198555]]
output we got at epoch  1045  
 [[0.91026649]
 [0.88582289]
 [0.1817517 ]]
output we got at epoch  1046  
 [[0.91038666]
 [0.88595654]
 [0.18151857]]
output we got at epoch  1047  
 [[0.91050646]
 [0.88608983]
 [0.18128615]]
output we got at epoch  1048  
 [[0.91062588]
 [0.88622273]
 [0.18105445]]
output we got at epoch  1049  
 [[0.91074493]
 [0.88635527]
 [0.18082345]]
output we got at epoch  1050  
 [[0.9108636 ]
 [0.88648744]
 [0.18059316]]
output we 

 [[0.93347961]
 [0.91253076]
 [0.13631631]]
output we got at epoch  1324  
 [[0.93353747]
 [0.91259959]
 [0.13620198]]
output we got at epoch  1325  
 [[0.93359519]
 [0.91266828]
 [0.1360879 ]]
output we got at epoch  1326  
 [[0.9336528 ]
 [0.91273683]
 [0.13597407]]
output we got at epoch  1327  
 [[0.93371027]
 [0.91280524]
 [0.13586047]]
output we got at epoch  1328  
 [[0.93376762]
 [0.91287351]
 [0.13574712]]
output we got at epoch  1329  
 [[0.93382485]
 [0.91294165]
 [0.13563401]]
output we got at epoch  1330  
 [[0.93388195]
 [0.91300964]
 [0.13552114]]
output we got at epoch  1331  
 [[0.93393893]
 [0.91307751]
 [0.13540851]]
output we got at epoch  1332  
 [[0.93399578]
 [0.91314523]
 [0.13529612]]
output we got at epoch  1333  
 [[0.93405251]
 [0.91321282]
 [0.13518397]]
output we got at epoch  1334  
 [[0.93410912]
 [0.91328027]
 [0.13507206]]
output we got at epoch  1335  
 [[0.9341656 ]
 [0.91334759]
 [0.13496038]]
output we got at epoch  1336  
 [[0.93422196]
 [0.913414

output we got at epoch  1593  
 [[0.94556402]
 [0.92715379]
 [0.11231189]]
output we got at epoch  1594  
 [[0.94559866]
 [0.92719642]
 [0.11224272]]
output we got at epoch  1595  
 [[0.94563324]
 [0.92723898]
 [0.11217366]]
output we got at epoch  1596  
 [[0.94566776]
 [0.92728147]
 [0.11210472]]
output we got at epoch  1597  
 [[0.94570223]
 [0.9273239 ]
 [0.11203589]]
output we got at epoch  1598  
 [[0.94573664]
 [0.92736626]
 [0.11196717]]
output we got at epoch  1599  
 [[0.94577099]
 [0.92740856]
 [0.11189856]]
output we got at epoch  1600  
 [[0.94580529]
 [0.92745079]
 [0.11183006]]
output we got at epoch  1601  
 [[0.94583953]
 [0.92749295]
 [0.11176167]]
output we got at epoch  1602  
 [[0.94587371]
 [0.92753505]
 [0.11169339]]
output we got at epoch  1603  
 [[0.94590784]
 [0.92757709]
 [0.11162522]]
output we got at epoch  1604  
 [[0.94594191]
 [0.92761906]
 [0.11155716]]
output we got at epoch  1605  
 [[0.94597593]
 [0.92766096]
 [0.11148921]]
output we got at epoch  1

output we got at epoch  1823  
 [[0.95227231]
 [0.93548503]
 [0.09887715]]
output we got at epoch  1824  
 [[0.95229687]
 [0.93551581]
 [0.09882782]]
output we got at epoch  1825  
 [[0.9523214 ]
 [0.93554655]
 [0.09877856]]
output we got at epoch  1826  
 [[0.95234589]
 [0.93557725]
 [0.09872936]]
output we got at epoch  1827  
 [[0.95237035]
 [0.93560791]
 [0.09868023]]
output we got at epoch  1828  
 [[0.95239478]
 [0.93563854]
 [0.09863116]]
output we got at epoch  1829  
 [[0.95241917]
 [0.93566912]
 [0.09858216]]
output we got at epoch  1830  
 [[0.95244353]
 [0.93569966]
 [0.09853323]]
output we got at epoch  1831  
 [[0.95246786]
 [0.93573017]
 [0.09848436]]
output we got at epoch  1832  
 [[0.95249215]
 [0.93576063]
 [0.09843555]]
output we got at epoch  1833  
 [[0.95251642]
 [0.93579106]
 [0.09838681]]
output we got at epoch  1834  
 [[0.95254065]
 [0.93582145]
 [0.09833813]]
output we got at epoch  1835  
 [[0.95256484]
 [0.9358518 ]
 [0.09828952]]
output we got at epoch  1

output we got at epoch  2123  
 [[0.95840978]
 [0.94324016]
 [0.0865177 ]]
output we got at epoch  2124  
 [[0.95842683]
 [0.94326188]
 [0.08648326]]
output we got at epoch  2125  
 [[0.95844387]
 [0.94328359]
 [0.08644886]]
output we got at epoch  2126  
 [[0.95846089]
 [0.94330527]
 [0.0864145 ]]
output we got at epoch  2127  
 [[0.95847789]
 [0.94332692]
 [0.08638018]]
output we got at epoch  2128  
 [[0.95849487]
 [0.94334856]
 [0.0863459 ]]
output we got at epoch  2129  
 [[0.95851183]
 [0.94337017]
 [0.08631165]]
output we got at epoch  2130  
 [[0.95852877]
 [0.94339176]
 [0.08627743]]
output we got at epoch  2131  
 [[0.9585457 ]
 [0.94341333]
 [0.08624326]]
output we got at epoch  2132  
 [[0.9585626 ]
 [0.94343488]
 [0.08620912]]
output we got at epoch  2133  
 [[0.95857949]
 [0.9434564 ]
 [0.08617502]]
output we got at epoch  2134  
 [[0.95859636]
 [0.9434779 ]
 [0.08614095]]
output we got at epoch  2135  
 [[0.95861322]
 [0.94349938]
 [0.08610692]]
output we got at epoch  2

output we got at epoch  2423  
 [[0.96281386]
 [0.94888256]
 [0.07760989]]
output we got at epoch  2424  
 [[0.9628265 ]
 [0.94889885]
 [0.07758427]]
output we got at epoch  2425  
 [[0.96283913]
 [0.94891513]
 [0.07755868]]
output we got at epoch  2426  
 [[0.96285175]
 [0.94893139]
 [0.07753311]]
output we got at epoch  2427  
 [[0.96286436]
 [0.94894763]
 [0.07750756]]
output we got at epoch  2428  
 [[0.96287696]
 [0.94896387]
 [0.07748204]]
output we got at epoch  2429  
 [[0.96288954]
 [0.94898009]
 [0.07745654]]
output we got at epoch  2430  
 [[0.96290212]
 [0.94899629]
 [0.07743106]]
output we got at epoch  2431  
 [[0.96291468]
 [0.94901248]
 [0.0774056 ]]
output we got at epoch  2432  
 [[0.96292723]
 [0.94902866]
 [0.07738017]]
output we got at epoch  2433  
 [[0.96293977]
 [0.94904482]
 [0.07735476]]
output we got at epoch  2434  
 [[0.9629523 ]
 [0.94906097]
 [0.07732937]]
output we got at epoch  2435  
 [[0.96296481]
 [0.9490771 ]
 [0.07730401]]
output we got at epoch  2

output we got at epoch  2723  
 [[0.96615483]
 [0.95320574]
 [0.07083138]]
output we got at epoch  2724  
 [[0.96616464]
 [0.9532185 ]
 [0.07081145]]
output we got at epoch  2725  
 [[0.96617445]
 [0.95323124]
 [0.07079153]]
output we got at epoch  2726  
 [[0.96618424]
 [0.95324397]
 [0.07077162]]
output we got at epoch  2727  
 [[0.96619403]
 [0.95325669]
 [0.07075173]]
output we got at epoch  2728  
 [[0.96620382]
 [0.95326941]
 [0.07073186]]
output we got at epoch  2729  
 [[0.96621359]
 [0.95328211]
 [0.070712  ]]
output we got at epoch  2730  
 [[0.96622336]
 [0.95329481]
 [0.07069216]]
output we got at epoch  2731  
 [[0.96623312]
 [0.95330749]
 [0.07067233]]
output we got at epoch  2732  
 [[0.96624287]
 [0.95332017]
 [0.07065252]]
output we got at epoch  2733  
 [[0.96625262]
 [0.95333283]
 [0.07063272]]
output we got at epoch  2734  
 [[0.96626235]
 [0.95334549]
 [0.07061294]]
output we got at epoch  2735  
 [[0.96627208]
 [0.95335813]
 [0.07059317]]
output we got at epoch  2

output we got at epoch  3023  
 [[0.96879278]
 [0.95664512]
 [0.06546692]]
output we got at epoch  3024  
 [[0.96880066]
 [0.95665543]
 [0.06545088]]
output we got at epoch  3025  
 [[0.96880853]
 [0.95666574]
 [0.06543485]]
output we got at epoch  3026  
 [[0.9688164 ]
 [0.95667603]
 [0.06541883]]
output we got at epoch  3027  
 [[0.96882427]
 [0.95668632]
 [0.06540282]]
output we got at epoch  3028  
 [[0.96883213]
 [0.9566966 ]
 [0.06538682]]
output we got at epoch  3029  
 [[0.96883998]
 [0.95670688]
 [0.06537083]]
output we got at epoch  3030  
 [[0.96884783]
 [0.95671714]
 [0.06535486]]
output we got at epoch  3031  
 [[0.96885567]
 [0.95672741]
 [0.06533889]]
output we got at epoch  3032  
 [[0.96886351]
 [0.95673766]
 [0.06532293]]
output we got at epoch  3033  
 [[0.96887134]
 [0.95674791]
 [0.06530699]]
output we got at epoch  3034  
 [[0.96887917]
 [0.95675815]
 [0.06529106]]
output we got at epoch  3035  
 [[0.96888699]
 [0.95676838]
 [0.06527513]]
output we got at epoch  3

output we got at epoch  3323  
 [[0.97093928]
 [0.95946052]
 [0.06109412]]
output we got at epoch  3324  
 [[0.97094577]
 [0.95946907]
 [0.06108088]]
output we got at epoch  3325  
 [[0.97095227]
 [0.9594776 ]
 [0.06106764]]
output we got at epoch  3326  
 [[0.97095876]
 [0.95948614]
 [0.06105441]]
output we got at epoch  3327  
 [[0.97096524]
 [0.95949467]
 [0.06104119]]
output we got at epoch  3328  
 [[0.97097172]
 [0.95950319]
 [0.06102798]]
output we got at epoch  3329  
 [[0.9709782 ]
 [0.95951171]
 [0.06101477]]
output we got at epoch  3330  
 [[0.97098467]
 [0.95952022]
 [0.06100158]]
output we got at epoch  3331  
 [[0.97099114]
 [0.95952873]
 [0.06098839]]
output we got at epoch  3332  
 [[0.97099761]
 [0.95953724]
 [0.0609752 ]]
output we got at epoch  3333  
 [[0.97100407]
 [0.95954574]
 [0.06096203]]
output we got at epoch  3334  
 [[0.97101053]
 [0.95955423]
 [0.06094886]]
output we got at epoch  3335  
 [[0.97101698]
 [0.95956272]
 [0.06093571]]
output we got at epoch  3

output we got at epoch  3623  
 [[0.97272728]
 [0.96181715]
 [0.05744654]]
output we got at epoch  3624  
 [[0.97273275]
 [0.96182438]
 [0.05743538]]
output we got at epoch  3625  
 [[0.97273822]
 [0.9618316 ]
 [0.05742422]]
output we got at epoch  3626  
 [[0.97274368]
 [0.96183881]
 [0.05741307]]
output we got at epoch  3627  
 [[0.97274914]
 [0.96184602]
 [0.05740193]]
output we got at epoch  3628  
 [[0.97275459]
 [0.96185323]
 [0.05739079]]
output we got at epoch  3629  
 [[0.97276005]
 [0.96186043]
 [0.05737966]]
output we got at epoch  3630  
 [[0.9727655 ]
 [0.96186763]
 [0.05736854]]
output we got at epoch  3631  
 [[0.97277094]
 [0.96187483]
 [0.05735742]]
output we got at epoch  3632  
 [[0.97277639]
 [0.96188202]
 [0.0573463 ]]
output we got at epoch  3633  
 [[0.97278183]
 [0.96188921]
 [0.0573352 ]]
output we got at epoch  3634  
 [[0.97278727]
 [0.96189639]
 [0.05732409]]
output we got at epoch  3635  
 [[0.9727927 ]
 [0.96190357]
 [0.057313  ]]
output we got at epoch  3

 [0.05435676]]
output we got at epoch  3923  
 [[0.97424483]
 [0.96382546]
 [0.05434719]]
output we got at epoch  3924  
 [[0.9742495 ]
 [0.96383167]
 [0.05433763]]
output we got at epoch  3925  
 [[0.97425418]
 [0.96383787]
 [0.05432807]]
output we got at epoch  3926  
 [[0.97425886]
 [0.96384407]
 [0.05431852]]
output we got at epoch  3927  
 [[0.97426353]
 [0.96385026]
 [0.05430897]]
output we got at epoch  3928  
 [[0.9742682 ]
 [0.96385645]
 [0.05429942]]
output we got at epoch  3929  
 [[0.97427287]
 [0.96386264]
 [0.05428988]]
output we got at epoch  3930  
 [[0.97427753]
 [0.96386883]
 [0.05428035]]
output we got at epoch  3931  
 [[0.9742822 ]
 [0.96387502]
 [0.05427082]]
output we got at epoch  3932  
 [[0.97428686]
 [0.9638812 ]
 [0.0542613 ]]
output we got at epoch  3933  
 [[0.97429152]
 [0.96388737]
 [0.05425178]]
output we got at epoch  3934  
 [[0.97429618]
 [0.96389355]
 [0.05424226]]
output we got at epoch  3935  
 [[0.97430083]
 [0.96389972]
 [0.05423275]]
output we 

 [[0.97554862]
 [0.96555687]
 [0.05168189]]
output we got at epoch  4223  
 [[0.97555268]
 [0.96556228]
 [0.05167358]]
output we got at epoch  4224  
 [[0.97555674]
 [0.96556768]
 [0.05166528]]
output we got at epoch  4225  
 [[0.9755608 ]
 [0.96557308]
 [0.05165698]]
output we got at epoch  4226  
 [[0.97556486]
 [0.96557847]
 [0.05164868]]
output we got at epoch  4227  
 [[0.97556891]
 [0.96558387]
 [0.05164039]]
output we got at epoch  4228  
 [[0.97557297]
 [0.96558926]
 [0.05163209]]
output we got at epoch  4229  
 [[0.97557702]
 [0.96559465]
 [0.05162381]]
output we got at epoch  4230  
 [[0.97558107]
 [0.96560004]
 [0.05161552]]
output we got at epoch  4231  
 [[0.97558512]
 [0.96560542]
 [0.05160725]]
output we got at epoch  4232  
 [[0.97558917]
 [0.96561081]
 [0.05159897]]
output we got at epoch  4233  
 [[0.97559321]
 [0.96561619]
 [0.0515907 ]]
output we got at epoch  4234  
 [[0.97559725]
 [0.96562156]
 [0.05158243]]
output we got at epoch  4235  
 [[0.97560129]
 [0.965626

 [[0.9766907 ]
 [0.96707809]
 [0.04934534]]
output we got at epoch  4523  
 [[0.97669427]
 [0.96708285]
 [0.04933804]]
output we got at epoch  4524  
 [[0.97669784]
 [0.9670876 ]
 [0.04933074]]
output we got at epoch  4525  
 [[0.9767014 ]
 [0.96709236]
 [0.04932344]]
output we got at epoch  4526  
 [[0.97670496]
 [0.96709711]
 [0.04931615]]
output we got at epoch  4527  
 [[0.97670852]
 [0.96710186]
 [0.04930887]]
output we got at epoch  4528  
 [[0.97671208]
 [0.96710661]
 [0.04930158]]
output we got at epoch  4529  
 [[0.97671564]
 [0.96711135]
 [0.0492943 ]]
output we got at epoch  4530  
 [[0.9767192 ]
 [0.9671161 ]
 [0.04928702]]
output we got at epoch  4531  
 [[0.97672275]
 [0.96712084]
 [0.04927974]]
output we got at epoch  4532  
 [[0.97672631]
 [0.96712558]
 [0.04927247]]
output we got at epoch  4533  
 [[0.97672986]
 [0.96713032]
 [0.0492652 ]]
output we got at epoch  4534  
 [[0.97673341]
 [0.96713505]
 [0.04925793]]
output we got at epoch  4535  
 [[0.97673696]
 [0.967139

output we got at epoch  4822  
 [[0.97769834]
 [0.96842377]
 [0.04728245]]
output we got at epoch  4823  
 [[0.97770151]
 [0.968428  ]
 [0.04727598]]
output we got at epoch  4824  
 [[0.97770467]
 [0.96843223]
 [0.0472695 ]]
output we got at epoch  4825  
 [[0.97770783]
 [0.96843645]
 [0.04726303]]
output we got at epoch  4826  
 [[0.97771099]
 [0.96844068]
 [0.04725656]]
output we got at epoch  4827  
 [[0.97771414]
 [0.9684449 ]
 [0.04725009]]
output we got at epoch  4828  
 [[0.9777173 ]
 [0.96844912]
 [0.04724363]]
output we got at epoch  4829  
 [[0.97772045]
 [0.96845334]
 [0.04723717]]
output we got at epoch  4830  
 [[0.97772361]
 [0.96845756]
 [0.04723071]]
output we got at epoch  4831  
 [[0.97772676]
 [0.96846177]
 [0.04722425]]
output we got at epoch  4832  
 [[0.97772991]
 [0.96846599]
 [0.0472178 ]]
output we got at epoch  4833  
 [[0.97773306]
 [0.9684702 ]
 [0.04721135]]
output we got at epoch  4834  
 [[0.97773621]
 [0.96847441]
 [0.0472049 ]]
output we got at epoch  4